### ISSUE TITLE
Many of the results are incorrect.

### ISSUE THREAD

**Issue by jiangzhiping** [Max-Gulda/Cordic-Math#14]
The results of `cordic-exp` and `cordic-pow` are incorrect.

**Comment by Max-Gulda** [comment]
Could you please tell me what numbers you tried and what the answers was?

**Comment by Max-Gulda** [comment]
The issues are due to overflow in fixed-point arithmetic. I’ve improved the code to handle larger numbers by using 64-bit integers for intermediate calculations. It can now compute values like 2^14, but larger values may still cause overflow.
